# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_document_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uri',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='space',
            name='uri',
        ),
        migrations.AddField(
            model_name='space',
            name='path',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
