# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_populate_default_spaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('view_document', 'Can view a document'),)},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'permissions': (('view_space', 'Can view a space'),)},
        ),
    ]
