# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 07:14
from __future__ import unicode_literals

from django.db import migrations

def create_admin_group(apps, schema_editor):
    """ Create a spaces admin group """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Cascading permissions
    # Starting from the most senior, only list the permissions that the
    # other groups do not.
    group_permissions = {
        "admin": ["add_group", "change_group", "delete_group",
                  "add_permission", "change_permission", "delete_permission",
                  "add_user", "change_user", "delete_user",
                  "add_space", "change_space", "delete_space" ],
        "editor": ["add_document", "change_document", "delete_document",
                   "add_revision", "change_revision", "delete_revision",
                   "add_comment", "change_comment", "delete_comment"],
        "viewer": ["view_document", "view_space"]
    }

    admin = Group.objects.create(name="Spaces Admin")
    editor = Group.objects.create(name="Spaces Editor")
    viewer = Group.objects.create(name="Spaces Viewer")

    # Apply permissions
    for group, perm_list in group_permissions.iteritems():
        for p in perm_list:
            try:
                perm = Permission.objects.get(codename=p)

                admin.permissions.add(perm)
                if group == "editor":
                    editor.permissions.add(perm)
                elif group == "viewer":
                    editor.permissions.add(perm)
                    viewer.permissions.add(perm)
            except:
                pass


def rollback_admin_group(apps, schema_editor):
    """ Delete spaces admin group """
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name="Spaces Admin").delete()
    Group.objects.get(name="Spaces Editor").delete()
    Group.objects.get(name="Spaces Viewer").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_model_permissions'),
    ]

    operations = [
    migrations.RunPython(create_admin_group, rollback_admin_group),
    ]
