# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_spaces_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='space_doc',
            field=models.BooleanField(default=False, verbose_name=b'Is this the space root document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'URL Slug'),
        ),
    ]
