# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_document_space_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='path',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('path', 'parent')]),
        ),
    ]
