# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_unique_space_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='space_doc',
        ),
        migrations.AddField(
            model_name='document',
            name='is_space_root',
            field=models.BooleanField(default=False, verbose_name=b"Is this a space's root document"),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
